[package]
name = "acp"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Access Control Policy for DefraDB"

[features]
default = ["native"]
native = []

[lib]
bench = false

[dependencies]
defra-core = { path = "../defra-core" }
identity = { path = "../identity" }
storage = { path = "../storage" }
zanzibar = { path = "../zanzibar" }

async-trait.workspace = true
async-lock.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
rapidhash.workspace = true
tracing.workspace = true
sha2.workspace = true
serde_yaml = "0.9"

[dev-dependencies]
bytes = { workspace = true }
tempfile = "3"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "test-util"] }

[lints]
workspace = true
