[package]
name = "schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.cargo-machete]
ignored = ["serde_ipld_dagcbor"]

[lib]
bench = false

[dependencies]
defra-core = { path = "../defra-core" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_ipld_dagcbor.workspace = true
cid.workspace = true
multihash.workspace = true
rapidhash.workspace = true
sha2.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
