use async_trait::async_trait;
use db::{AutoCommitMutator, DB};
use defra_core::encryption::{set_encryption_config, EncryptionConfig};
use document::Document;
use query::mutator::{DocMutator, MutationBatchController};
use schema::{CollectionVersion, FieldDescription, FieldKind};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;
use storage::RegolithStore;

#[derive(Default)]
pub(super) struct CountingKms(pub(super) AtomicUsize);

#[async_trait]
impl kms::KmsService for CountingKms {
    async fn generate_key(
        &self,
        _: &kms::RequestContext,
        scope: kms::KeyScope,
    ) -> kms::Result<(kms::EncryptionCid, [u8; 32])> {
        assert!(matches!(scope, kms::KeyScope::Document { .. }));
        let count = self.0.fetch_add(1, Ordering::SeqCst) + 1;
        let key = [u8::try_from(count).unwrap(); 32];
        let block = defra_core::Encryption { key: key.to_vec() };
        let cid =
            defra_core::block::generate_cid_from_bytes(&block.to_dag_cbor().unwrap()).unwrap();
        Ok((cid, key))
    }

    async fn get_keys(
        &self,
        _: &kms::RequestContext,
        cids: &[kms::EncryptionCid],
    ) -> kms::Result<kms::KeyResults> {
        let (results, sender) = kms::KeyResults::new(cids.len());
        for cid in cids {
            let mut found = None;
            for count in 1..=self.0.load(Ordering::SeqCst) {
                let key = [u8::try_from(count).unwrap(); 32];
                let block = defra_core::Encryption { key: key.to_vec() };
                if defra_core::block::generate_cid_from_bytes(&block.to_dag_cbor().unwrap())
                    .unwrap()
                    == *cid
                {
                    found = Some(key);
                    break;
                }
            }
            sender
                .send(Ok((*cid, found.expect("key was generated by this KMS"))))
                .await
                .unwrap();
        }
        drop(sender);
        Ok(results)
    }

    async fn serve_request(
        &self,
        _: kms::PeerIdentity,
        _: kms::FetchEncryptionKeyRequest,
    ) -> kms::Result<kms::FetchEncryptionKeyReply> {
        Err(kms::Error::Unsupported("unexpected peer request"))
    }
}

pub(super) struct Fixture {
    pub(super) db: Arc<DB<RegolithStore>>,
    pub(super) kms: Arc<CountingKms>,
}

impl Drop for Fixture {
    fn drop(&mut self) {
        set_encryption_config(None);
    }
}

pub(super) async fn fixture() -> Fixture {
    let db = Arc::new(DB::new(RegolithStore::in_memory().unwrap()).unwrap());
    let kms = Arc::new(CountingKms::default());
    db.set_kms(kms.clone());
    db.create_collection(CollectionVersion::new(
        "Secrets",
        "secrets-v1",
        "col-secrets",
        vec![
            FieldDescription::new("1", "_docID", FieldKind::doc_id()),
            FieldDescription::new("2", "left", FieldKind::string()),
            FieldDescription::new("3", "right", FieldKind::string()),
            FieldDescription::new("4", "public", FieldKind::string()),
        ],
    ))
    .await
    .unwrap();
    Fixture { db, kms }
}

fn encrypt() {
    set_encryption_config(Some(EncryptionConfig {
        encrypt_doc: false,
        encrypt_fields: vec!["left".to_string(), "right".to_string()],
    }));
}

fn document(value: &str) -> Document {
    let mut doc = Document::new();
    doc.set("left", value);
    doc.set("right", value);
    doc.set("public", value);
    doc
}

#[tokio::test]
async fn autocommit_create_mints_one_kms_key_per_encrypted_field() {
    let fixture = fixture().await;
    encrypt();
    AutoCommitMutator::new(Arc::clone(&fixture.db))
        .create("Secrets", document("first"))
        .await
        .unwrap();
    assert_eq!(fixture.kms.0.load(Ordering::SeqCst), 2);
}

#[tokio::test]
async fn create_many_mints_one_kms_key_per_encrypted_field() {
    let fixture = fixture().await;
    encrypt();
    AutoCommitMutator::new(Arc::clone(&fixture.db))
        .create_many("Secrets", vec![document("first"), document("second")])
        .await
        .unwrap();
    assert_eq!(fixture.kms.0.load(Ordering::SeqCst), 4);
}

#[tokio::test]
async fn batch_create_mints_one_kms_key_per_encrypted_field() {
    let fixture = fixture().await;
    let (batch, fetcher) = AutoCommitMutator::new(Arc::clone(&fixture.db))
        .new_batch_components()
        .await
        .unwrap();
    encrypt();
    batch.create("Secrets", document("first")).await.unwrap();
    drop(fetcher);
    batch.commit().await.unwrap();
    assert_eq!(fixture.kms.0.load(Ordering::SeqCst), 2);
}

#[tokio::test]
async fn autocommit_update_mints_one_kms_key_per_encrypted_field() {
    let fixture = fixture().await;
    let mutator = AutoCommitMutator::new(Arc::clone(&fixture.db));
    let created = mutator.create("Secrets", document("first")).await.unwrap();
    let mut doc = document("second");
    doc.set_id(created.doc_id);
    encrypt();
    mutator
        .update(
            "Secrets",
            doc,
            ["left".to_string(), "right".to_string()]
                .into_iter()
                .collect(),
        )
        .await
        .unwrap();
    assert_eq!(fixture.kms.0.load(Ordering::SeqCst), 2);
}

#[tokio::test]
async fn batch_update_mints_one_kms_key_per_encrypted_field() {
    let fixture = fixture().await;
    let mutator = AutoCommitMutator::new(Arc::clone(&fixture.db));
    let created = mutator.create("Secrets", document("first")).await.unwrap();
    let (batch, fetcher) = mutator.new_batch_components().await.unwrap();
    let mut doc = document("second");
    doc.set_id(created.doc_id);
    encrypt();
    batch
        .update(
            "Secrets",
            doc,
            ["left".to_string(), "right".to_string()]
                .into_iter()
                .collect(),
        )
        .await
        .unwrap();
    drop(fetcher);
    batch.commit().await.unwrap();
    assert_eq!(fixture.kms.0.load(Ordering::SeqCst), 2);
}

#[tokio::test]
async fn batch_inherits_whole_document_encryption_for_a_new_field() {
    let fixture = fixture().await;
    let (batch, fetcher) = AutoCommitMutator::new(Arc::clone(&fixture.db))
        .new_batch_components()
        .await
        .unwrap();
    set_encryption_config(Some(EncryptionConfig {
        encrypt_doc: true,
        encrypt_fields: Vec::new(),
    }));
    let created = batch
        .create(
            "Secrets",
            Document::from_json_str(r#"{"left":"one"}"#).unwrap(),
        )
        .await
        .unwrap();
    set_encryption_config(None);
    let mut doc = created.document;
    doc.set("right", "two");
    batch
        .update("Secrets", doc, ["right".to_string()].into_iter().collect())
        .await
        .unwrap();
    drop(fetcher);
    batch.commit().await.unwrap();
    assert_eq!(fixture.kms.0.load(Ordering::SeqCst), 2);
}
