[package]
name = "defra-trace"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
bench = false

[dependencies]
fastrace.workspace = true
defra-trace-macro = { path = "../trace-macro" }

[lints]
workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
